=== dmitry-izmerov/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        <!--<xs:key name="PK_Users">
            <xs:selector xpath="Payload/Users/User"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="FK_Group_To_Users" refer="PK_Users">
            <xs:selector xpath="Group/Participant"/>
            <xs:field xpath="@userId"/>
        </xs:keyref>-->
    </xs:element>

    <xs:element name="Project">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="Group"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="xs:string" name="description" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Group">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Participant">
                    <xs:complexType>
                        <xs:attribute name="user" type="xs:IDREF"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute type="groupType" name="type" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="User" type="userType"/>
    <xs:element name="City" type="cityType"/>

    <xs:simpleType name="groupType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="userType">
        <xs:sequence minOccurs="0">
            <xs:element type="xs:string" name="fullName"/>
        </xs:sequence>
        <xs:attribute type="xs:ID" name="id" use="required"/>
        <xs:attribute type="xs:string" name="email" use="required"/>
        <xs:attribute type="flagType" name="flag" use="required"/>
        <xs:attribute type="xs:IDREF" name="city"/>
    </xs:complexType>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== dmitry-izmerov/masterjava/src/main/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User id="u1" flag="active" city="kiv" email="gmail@gmail.com">
            <fullName>Full Name</fullName>
        </User>
        <User id="u2" flag="superuser" city="spb" email="admin@javaops.ru">
            <fullName>Admin</fullName>
        </User>
        <User id="u3" flag="deleted" city="spb" email="mail@yandex.ru">
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project name="Spring Basics">
            <Group name="Spring Core" type="CURRENT">
                <Participant user="u1"/>
                <Participant user="u2"/>
            </Group>
            <Group name="Spring Boot" type="REGISTERING">
                <Participant user="u2"/>
                <Participant user="u3"/>
            </Group>
            <Group name="Spring Data" type="FINISHED">
                <Participant user="u1"/>
                <Participant user="u2"/>
                <Participant user="u3"/>
            </Group>
        </Project>
    </Projects>
</Payload>
